### ISSUE TITLE
Fatal Exception creating release build for Android/iOS

### ISSUE THREAD

**Issue by Diego-Franco** [apollographql/graphql-tag#183]
**Issue Labels**

- [ ] has-reproduction
- [ ] feature
- [ ] docs
- [x] blocking
- [ ] good first issue
I hope someone can help me with this problem.

I followed the Apollo documentation to setup graphql with my React Native project, if I run the application on test, I don't have any problem, but when my CI runs and create the build I got the following:

> 05-07 16:47:07.217 7985-8122/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.onedebit.chime, PID: 7985
    com.facebook.react.common.JavascriptException: undefined is not an object (evaluating 'L.prototype'), stack:
    <unknown>@1050:3054
    <unknown>@1050:847
    <unknown>@1050:1114
    d@2:768
    n@2:409
    t@2:262
.
.
.
        at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:56)
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:40)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at           com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThr   eadHandler.java:31)
        at android.os.Looper.loop(Looper.java:168)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
        at java.lang.Thread.run(Thread.java:818)
05-07 16:47:07.217 907-3127/? E/ActivityManager: App crashed! Process:

And in my reports I got this 

<img width="459" alt="screen shot 2018-05-07 at 5 02 40 pm" src="https://user-images.githubusercontent.com/5623933/39730928-335a3fba-5219-11e8-97b4-f878580f5f0e.png">

**Comment by jnwng** [comment]
@Diego-Franco sorry that you're having trouble with this! unfortunately i dont have an android device to try and reproduce, but i went through and ran through as much as i could on react-native iOS to see if i could find something obviously wrong, but unfortunately i wasn't able to get very far.

in order to debug this further, here's what i could use from you:
1) what version of `graphql-tag` are you using?
2) can you confirm that you have installed a valid `graphql` package to fulfill the `peerDependency`?
3) is there any way for you to dive deeper into that stack to figure out what `L` is and where this is actually failing? is this failing within `graphql-tag` itself?

in order to make my workload a little more maintainable, im going to close this for now. please re-open if you're still having trouble and you have the things above!
