### ISSUE TITLE
How to import graphql file in graphql file??

### ISSUE THREAD

**Issue by Adherentman** [apollographql/graphql-tag#212]
**Issue Labels**

- [ ] has-reproduction
- [ ] feature
- [ ] docs
- [ ] blocking
- [x] good first issue

I use graphql-tag/loaders in webpack.
and I use webpack in backend;

The webpack aspect is normal, but I encountered an error when I was ready to start the project.

**This is webpack log，looked great, very successful.**
```shell
Hash: da549d2d052c01acc59f
Version: webpack 4.19.1
Time: 7739ms
Built at: 09/23/2018 4:13:43 PM
          Asset      Size  Chunks             Chunk Names
index.bundle.js  67.4 KiB   index  [emitted]  index
Entrypoint index = index.bundle.js
[./config/index.ts] 474 bytes {index} [built]
[./src/graphql/Root.graphql] 1.64 KiB {index} [built]
[./src/graphql/auth/Auth.graphql] 10.6 KiB {index} [built]
[./src/graphql/index.ts] 2.5 KiB {index} [built]
[./src/index.ts] 3.75 KiB {index} [built]
[./src/middleware/logger.ts] 4.45 KiB {index} [built]
[0] multi ./src/index.ts 28 bytes {index} [built]
[apollo-server-koa] external "apollo-server-koa" 42 bytes {index} [built]
[bunyan] external "bunyan" 42 bytes {index} [built]
[fs] external "fs" 42 bytes {index} [built]
[http] external "http" 42 bytes {index} [built]
[https] external "https" 42 bytes {index} [built]
[koa] external "koa" 42 bytes {index} [built]
[lodash] external "lodash" 42 bytes {index} [built]
[uuid] external "uuid" 42 bytes {index} [built]
    + 15 hidden modules
✨  Done in 8.52s.
```

**This is when I started the project, it was very bad.**
```shell
/Users/xuzihao/project/zh-backend/node_modules/graphql/utilities/buildASTSchema.js:84
        throw new Error("Type \"".concat(typeName, "\" was defined more than once."));
        ^
Error: Type "MessageResult" was defined more than once.
    at Object.buildASTSchema (/Users/xuzihao/project/zh-backend/node_modules/graphql/utilities/buildASTSchema.js:84:15)
    at Object.buildSchemaFromTypeDefinitions (/Users/xuzihao/project/zh-backend/node_modules/graphql-tools/dist/generate/buildSchemaFromTypeDefinitions.js:24:28)
    at Object.makeExecutableSchema (/Users/xuzihao/project/zh-backend/node_modules/graphql-tools/dist/makeExecutableSchema.js:27:29)
    at new ApolloServerBase (/Users/xuzihao/project/zh-backend/node_modules/apollo-server-core/dist/ApolloServer.js:106:43)
    at new ApolloServer (/Users/xuzihao/project/zh-backend/node_modules/apollo-server-koa/dist/ApolloServer.js:48:1)
    at eval (webpack:///./src/index.ts?:21:16)
    at Object../src/index.ts (/Users/xuzihao/project/zh-backend/dist/index.bundle.js:166:1)
    at __webpack_require__ (/Users/xuzihao/project/zh-backend/dist/index.bundle.js:20:30)
    at eval (webpack:///multi_./src/index.ts?:1:18)
    at Object.0 (/Users/xuzihao/project/zh-backend/dist/index.bundle.js:249:1)
```

this is my graphql file
root.graphql
```graphql
type Query {
  _empty: String @deprecated(reason: "")
}
type Mutation {
  _empty: String @deprecated(reason: "")
}
```

common.graphql
```graphql
type MessageResult {
  message: String
}
```

auth.graphql
```graphql
#import "../Common.graphql"

scalar Date
input LoginArgs {
  username: String!
  password: String!
}

input RegisterArgs {
  email: String!
  first_name: String!
  last_name: String!
  username: String!
  password: String!
  re_password: String!
}

input RestPasswdArgs {
  email: String!
  rest_passwd_key: String
  password: String!
  re_password: String!
}

input SendRestPasswordEmailArgs {
  email: String
}

type Auth {
  id: ID!
  email: String!
  first_name: String!
  last_name: String!
  username: String!
  password: String!
  re_password: String
  token: String
  rest_passwd_key: String
}

extend type Query {
  login: [Auth]
  loginResolver(
    loginArgs: LoginArgs
  ): Auth
}

extend type Mutation {
  registerResolver(
    registerArgs: RegisterArgs
  ): MessageResult
  restPassword(
    restpasswdArgs: RestPasswdArgs
  ): MessageResult
  sendRestPasswordEmail(
    sendRestPasswordEmailArgs: SendRestPasswordEmailArgs
  ): MessageResult
}
```

index.ts

```typescript

import * as authTypeDefs from './auth/Auth.graphql';
import * as commonTypeDefs from './Common.graphql';
import * as baseTypeDefs from './Root.graphql';

const typeDefs = [baseTypeDefs, authTypeDefs, commonTypeDefs];
```

**I don't know where I am having problems. Please instruct me thank you**

**Comment by Adherentman** [comment]
I think you must use webpack or gulp ，then copy graphql file to dist floder

**Comment by djchrispurple** [comment]
you can use lodash to import and merge the files
