### ISSUE TITLE
Error parsing .graphql file

### ISSUE THREAD

**Issue by sigfriedCub1990** [apollographql/graphql-tag#239]
Hello there, I'm having this issue and I can't understand what's happening, I have a project in Vue, I'm using apollo-vue and I needed to install `graphql-tag` to parse `.graphql|.gql` files but now I'm getting this error:  
```
 error  in ./src/graphql/paginas.query.graphql

Module build failed (from ./node_modules/graphql-tag/loader.js):
GraphQLError: Syntax Error: Unexpected Name "var"
    at syntaxError (/home/sigfried/develop/p1stache/PalacioMetropolitano/node_modules/graphql/error/syntaxError.js:24:10)
    at unexpected (/home/sigfried/develop/p1stache/PalacioMetropolitano/node_modules/graphql/language/parser.js:1483:33)
    at parseDefinition (/home/sigfried/develop/p1stache/PalacioMetropolitano/node_modules/graphql/language/parser.js:155:9)
    at many (/home/sigfried/develop/p1stache/PalacioMetropolitano/node_modules/graphql/language/parser.js:1513:16)
    at parseDocument (/home/sigfried/develop/p1stache/PalacioMetropolitano/node_modules/graphql/language/parser.js:115:18)
    at parse (/home/sigfried/develop/p1stache/PalacioMetropolitano/node_modules/graphql/language/parser.js:50:10)
    at parseDocument (/home/sigfried/develop/p1stache/PalacioMetropolitano/node_modules/graphql-tag/src/index.js:129:16)
    at gql (/home/sigfried/develop/p1stache/PalacioMetropolitano/node_modules/graphql-tag/src/index.js:170:10)
    at Object.module.exports (/home/sigfried/develop/p1stache/PalacioMetropolitano/node_modules/graphql-tag/loader.js:44:18)

 @ ./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/.cache/vue-loader","cacheIdentifier":"17af8544-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Bodas.vue?vue&type=template&id=763c81df&scoped=true& 24:24-66
 @ ./src/views/Bodas.vue?vue&type=template&id=763c81df&scoped=true&
 @ ./src/views/Bodas.vue
 @ ./src/router.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.10.112:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```
**I'm using:**
```
"graphql-tag": "^2.10.1"
```
Any light on this is really appreciated. Thank you

**Comment by jnwng** [comment]
im not super familiar with vue, so it'd be helpful to see what that `.graphql` file looks like. off the top of my head, however, this typically comes up if you run the loader twice, since the first pass will translate the `.graphql` file into a [JavaScript module](https://github.com/apollographql/graphql-tag/blob/50a850e484a60d95ddb99801c39785031e55b7a2/loader.js#L46)

please re-open if you're still having an issue!

**Comment by sandwichsudo** [comment]
In case this helps someone: mine was tripping up on my graphql schema, which is a different kind of file, that I was loading with 

```
    const schema = makeExecutableSchema({
        typeDefs: require('raw-loader!../schema.graphql'),
        ...schemaOptions,
    });
```

**Comment by olyop** [comment]
I had the same error.
For me it was due to using the loader twice in my webpack configuration (in my base config).
