### ISSUE TITLE
External fragments are not pulled into the query document using the loader IN FINAL IMPORT

### ISSUE THREAD

**Issue by emahuni** [apollographql/graphql-tag#268]
It's sort of related to #53, but the issue here is that the final import doesn't seem to contain the fragment:

contact.fragment.graphql:
```graphql
fragment fullContactFields on Contact {
  addresses {
    line1
    line2
  }
  mobiles {
    number
  }
}
```

profile.graphql:
```graphql
# import '../fragments/contact.fragment.graphql'

query fetchProfile{
  profiles{
    firstname
    lastname
    contact {
      ...fullContactFields
    }
  }
}
```

then in js:

```js
import fetchProfileQ from './profile.graphql'

// vue-apollo
{
 apollo: 
    profiles:{
      query: fetchProfile
    }
}
```

results in the following error from the server: 

```js
0: {message: "Cannot read property 'kind' of undefined", extensions: {code: "INTERNAL_SERVER_ERROR",…}}
extensions: {code: "INTERNAL_SERVER_ERROR",…}
code: "INTERNAL_SERVER_ERROR"
exception: {stacktrace: ["TypeError: Cannot read property 'kind' of undefined",…]}
stacktrace: ["TypeError: Cannot read property 'kind' of undefined",…]
0: "TypeError: Cannot read property 'kind' of undefined"
1: "    at determineDepth (/Users/em/dev/projects/app/api/node_modules/graphql-depth-limit/index.js:60:16)"
2: "    at determineDepth (/Users/em/dev/projects/app/api/node_modules/graphql-depth-limit/index.js:72:14)"
...
```

Further console log scrutiny of the imported graphql query shows that the fragment definition is missing in the AST. 

**NOTICE** If I combine the two files into one (profile.graphql) then the fragment is defined in the resulting AST document and works flowlessly. 

Am I missing something I should do to include the fragment or it's a bug?

**Comment by emahuni** [comment]
I found an [article](https://blog.apollographql.com/webpacking-your-graphql-documents-bf9697ed259b) explaining exactly what I am doing and I am doing it right. There seems to be unexpected behaviour and a bug here.

**Comment by emahuni** [comment]
ok, just found out that there shouldn't be any space between the pound and import statement.

```grapql
#import "../fragments/contact.fragment.graphql"
# instead of
# import "../fragments/contact.fragment.graphql"
```

I wish the imports resolver was less strict.
