### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by betimer** [apollographql/graphql-tag#290]
Error: Cannot find module 'graphql/language/parser'

Require stack:

**Comment by codebling** [comment]
```
Error: Cannot find module 'graphql/language/parser'
Require stack:
- /project/node_modules/graphql-tag/lib/graphql-tag.umd.js
- /project/lib/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /project/node_modules/graphql-tag/src/index.js:1:14
    at /project/node_modules/graphql-tag/lib/graphql-tag.umd.js:2:65
    at Object.<anonymous> (/project/node_modules/graphql-tag/lib/graphql-tag.umd.js:5:2)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
```

**Comment by codebling** [comment]
@betimer looks like there is a peer dependency on `graphql`

```
  "peerDependencies": {
    "graphql": "^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0"
  }
```
