### ISSUE TITLE
How can I send a mutation parameter with embedded quotes?

### ISSUE THREAD

**Issue by SaucyJack** [apollographql/graphql-tag#296]
We have a situation where we will be sending data into a mutation that may have embedded quotes, among other fun special characters. If I write this in the playground, it works fine:

```
mutation {
  createThing(
    input:{
      related_object_id:1
      raw_data:"<?xml version=\"1.0\"?><root><something>whatever</something></root>"
    }
  ) {
    id
  }
}

```

But if I attempt to use graphql-tag in a test with the same, like this:

```
const { mutate } = require('apollo-server-testing')

const createThing = gql`
  mutation {
    createThing(
      input: {
        related_object_id: 1
        raw_data: "<?xml version=\"1.0\"?><root><something>whatever</something></root>"
      }
    )
  }
`
const res = await mutate({ mutation: createThing })
```

I get an error:

```
    GraphQLError: Syntax Error: Expected Name, found Float "1.0"

      at syntaxError (node_modules/graphql/error/syntaxError.js:15:10)
      at Parser.expectToken (node_modules/graphql/language/parser.js:1404:40)
      at Parser.parseName (node_modules/graphql/language/parser.js:94:22)
      at Parser.parseObjectField (node_modules/graphql/language/parser.js:579:21)
      at Parser.item (node_modules/graphql/language/parser.js:563:21)
      at Parser.any (node_modules/graphql/language/parser.js:1478:26)
      at Parser.parseObject (node_modules/graphql/language/parser.js:568:20)
      at Parser.parseValueLiteral (node_modules/graphql/language/parser.js:455:21)
      at Parser.parseArgument (node_modules/graphql/language/parser.js:333:19)
      at Parser.optionalMany (node_modules/graphql/language/parser.js:1497:28)
```

Similarly, if I try sending in JSON, like this:

```
const someObj = {
  name: 'whatever'
}
const createThing = gql`
  mutation {
    createThing(
      input: {
        related_object_id: 1
        raw_data: "${JSON.stringify(someObj)}"
      }
    )
  }
`
```

I get this error:

```
GraphQLError: Syntax Error: Expected :, found String ":"

      at syntaxError (node_modules/graphql/error/syntaxError.js:15:10)
      at Parser.expectToken (node_modules/graphql/language/parser.js:1404:40)
      at Parser.parseObjectField (node_modules/graphql/language/parser.js:580:10)
      at Parser.item (node_modules/graphql/language/parser.js:563:21)
      at Parser.any (node_modules/graphql/language/parser.js:1478:26)
      at Parser.parseObject (node_modules/graphql/language/parser.js:568:20)
      at Parser.parseValueLiteral (node_modules/graphql/language/parser.js:455:21)
      at Parser.parseArgument (node_modules/graphql/language/parser.js:333:19)
      at Parser.optionalMany (node_modules/graphql/language/parser.js:1497:28)
      at Parser.parseArguments (node_modules/graphql/language/parser.js:319:17)

```

How can I send parameter values into graphql-tag that have embedded quotes

**Comment by strtw** [comment]
@SaucyJack did you ever find a resolution for this?
