### ISSUE TITLE
BUG: Definitions written to `.gql`

### ISSUE THREAD

**Issue by will-holley** [apollographql/graphql-tag#323]
### Setup (within Next.js App)

**next.config.js** – Webpack Bundling Configuration
```javascript
module.exports = {
  webpack: (config, { buildId, dev, isServer, defaultLoaders, webpack }) => {
    config.module.rules.push({
      test: /\.(graphql|gql)$/,
      exclude: /node_modules/,
      loader: "graphql-tag/loader",
    });
    return config;
  },
};
```

**@/gql/fragments/FooDetails.gql**
```gql
fragment FooDetails on Foo {
  id
  name
}
```

**@/gql/queries/FetchBar.gql**
```gql
#import "../fragments/FooDetails.gql";

query FetchBar {
  bar {
    id
    name
    foos {
      ...FooDetails
    }
  }
}
```

**BarComponent.js**
```javascript
import FetchBar from "@/gql/queries/FetchBar.gql";

const BarComponent = () => {
  // queries bar, etc.
}
```

### Error Trace

```shell
@/gql/queries/FetchBar.gql 21:92
ModuleParseError: Module parse failed: Unexpected token (21:92)
File was processed with these loaders:
 * ./node_modules/graphql-tag/loader.js
You may need an additional loader to handle the result of these loaders.
|       )
|     }
>   doc.definitions = doc.definitions.concat(unique(require("../../fragments/FooDetails.gql";).definitions));
| 
| 
    at handleParseError (project/node_modules/webpack/lib/NormalModule.js:469:19)
    at project/node_modules/webpack/lib/NormalModule.js:503:5
    at project/node_modules/webpack/lib/NormalModule.js:358:12
    at project/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (project/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (project/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at project/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (project/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (project/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at project/node_modules/loader-runner/lib/LoaderRunner.js:205:4
    at project/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

**Comment by will-holley** [comment]
The trailing semicolon in `#import "../fragments/FooDetails.gql";` was syntactically invalid and removing this fixed the issue.

**Comment by fabianrichter** [comment]
> The trailing semicolon in `#import "../fragments/FooDetails.gql";` was syntactically invalid and removing this fixed the issue.

Thank you, you saved my day!
