### ISSUE TITLE
Module build failed: GraphQLError

### ISSUE THREAD

**Issue by devarashetty** [apollographql/graphql-tag#82]
I couldn't understand the error , I added `graphq-tag` to parse the `.graphql ` in webpack config file as shown below 

```{
      test: /\.(graphql|gql)$/,
      exclude: /node_modules/,
      loader: 'graphql-tag/loader',
    }
```

```
ERROR in ./src/modules/goin_users/client/graphql_queries/user_graphql_queries.graphql
[2] Module build failed: GraphQLError
[2]     at syntaxError (/home/sairam/Downloads/goin/goin/node_modules/graphql-tag/bundledParser.js:1349:16)
[2]     at unexpected (/home/sairam/Downloads/goin/goin/node_modules/graphql-tag/bundledParser.js:1043:34)
[2]     at parseDefinition (/home/sairam/Downloads/goin/goin/node_modules/graphql-tag/bundledParser.js:206:10)
[2]     at parseDocument (/home/sairam/Downloads/goin/goin/node_modules/graphql-tag/bundledParser.js:160:23)
[2]     at parse (/home/sairam/Downloads/goin/goin/node_modules/graphql-tag/bundledParser.js:97:11)
[2]     at parseDocument (/home/sairam/Downloads/goin/goin/node_modules/graphql-tag/index.js:125:16)
[2]     at gql (/home/sairam/Downloads/goin/goin/node_modules/graphql-tag/index.js:158:10)
[2]     at Object.module.exports (/home/sairam/Downloads/goin/goin/node_modules/graphql-tag/loader.js:27:18)

```

**Comment by jnwng** [comment]
@devarashetty do you mind sharing the `.graphql` file that's causing this?

**Comment by devarashetty** [comment]
```
import {gql} from 'react-apollo';

const query = gql`
  query {
    userCurrent{
      profile {
        name
      }
      appRoles,
      username,
      authEmail {
        address
      }
      orgs {
        userOrgRoles
        orgId
        name
        orgRoles
      }
      currentOrg {
        orgId
        userOrgRoles
        name
        orgRoles
      }
    }
  }`;

export default query;

```

**Comment by jnwng** [comment]
this works as expected with `graphql-tag@2.0.0`. do you mind sharing what version of react-apollo and graphql-tag you're using?

**Comment by devarashetty** [comment]
Sure @jnwng  , 
react-apollo - 1.2
graphql-tag- 1.3.2

**Comment by devarashetty** [comment]
I tried to insall graphql-tag using the command `npm install --save graphql-tag` but it still gives me the `1.3.2`

**Comment by jnwng** [comment]
@devarashetty is there anything holding you back from upgrading `react-apollo` to at least `v1.3.0`? if you're getting the same exact error as above, its likely that `react-apollo` is using its own version of `graphql-tag` and not the one that you just installed. we introduced the newest version of `graphql-tag` [here](https://github.com/apollographql/react-apollo/commit/6e8d529bf65b8e5aa86c7e9422b0c233a7a4a3c2) (v1.3.0). 

if its possible, can you try that and let me know if there's still an issue?

**Comment by devarashetty** [comment]
@jnwng  I am extremely sorry for delay response, I figured it out and the reason it happened because I gave regular query  on .graphql file where it expects only 
@[https://stackoverflow.com/questions/44242515/module-build-failed-graphqlerror]

**Comment by jnwng** [comment]
ah right, that makes sense. glad it was resolved!
